/**
 * Generates src/styles/digital-agency.css and digital-agency.tokens.json from the
 * Digital Agency Design System tokens (FR-008 / 16.x).
 *
 * Pipeline:
 *   @digital-go-jp/design-tokens + @digital-go-jp/tailwind-theme-plugin
 *     -> scripts/generate-theme.ts
 *       -> src/styles/digital-agency.css              (Tailwind v4 @theme + shadcn bridge)
 *          src/styles/digital-agency.tokens.json      (raw token snapshot)
 *            -> registry item: theme
 *
 * The @digital-go-jp packages are dev-only and never a consumer dependency; the
 * generated CSS is committed so consumers install nothing extra (FR-007).
 *
 * Run with `--check` to fail when regeneration would change the committed files
 * (FR-009 / CI-005).
 */
import { createRequire } from "node:module"
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, "..")
const STYLES = join(ROOT, "src", "styles")
const require = createRequire(import.meta.url)

const ATTRIBUTION = `/*
 * Portions derived from or inspired by digital-go-jp/design-system-example-components-react.
 * Original code licensed under the MIT License.
 * See THIRD_PARTY_LICENSES.md for details.
 *
 * digital-agency.css — GENERATED by scripts/generate-theme.ts. Do not edit by hand.
 * Source: @digital-go-jp/design-tokens + @digital-go-jp/tailwind-theme-plugin.
 */
`

type Theme = {
  colors?: Record<string, unknown>
  fontSize?: Record<string, unknown>
  fontWeight?: Record<string, string>
  lineHeight?: Record<string, string>
  fontFamily?: Record<string, string>
  borderRadius?: Record<string, string>
  boxShadow?: Record<string, string>
  screens?: Record<string, string>
}

function loadTheme(): Theme {
  const mod = require("@digital-go-jp/tailwind-theme-plugin")
  const plugin = typeof mod === "function" ? mod : (mod.default ?? mod)
  const cfg = (plugin as { config?: unknown }).config ?? plugin
  const theme = (cfg as { theme?: { extend?: Theme } }).theme
  return (theme?.extend ?? theme ?? {}) as Theme
}

function css(theme: Theme): string {
  const lines: string[] = ["@theme {"]

  // Colors -> --color-<name>[-<shade>]
  lines.push("  /* colors */")
  for (const [name, value] of Object.entries(theme.colors ?? {})) {
    if (typeof value === "string") {
      lines.push(`  --color-${name}: ${value};`)
    } else if (value && typeof value === "object") {
      for (const [shade, v] of Object.entries(
        value as Record<string, string>
      )) {
        if (typeof v === "string")
          lines.push(`  --color-${name}-${shade}: ${v};`)
      }
    }
  }

  // Font size tuples -> --text-<name> (+ line-height / font-weight / letter-spacing)
  lines.push("\n  /* typography */")
  for (const [name, value] of Object.entries(theme.fontSize ?? {})) {
    if (Array.isArray(value)) {
      const [size, meta] = value as [string, Record<string, string>]
      lines.push(`  --text-${name}: ${size};`)
      if (meta?.lineHeight)
        lines.push(`  --text-${name}--line-height: ${meta.lineHeight};`)
      if (meta?.fontWeight)
        lines.push(`  --text-${name}--font-weight: ${meta.fontWeight};`)
      if (meta?.letterSpacing)
        lines.push(`  --text-${name}--letter-spacing: ${meta.letterSpacing};`)
    } else if (typeof value === "string") {
      lines.push(`  --text-${name}: ${value};`)
    }
  }

  for (const [name, v] of Object.entries(theme.fontWeight ?? {}))
    lines.push(`  --font-weight-${name}: ${v};`)
  for (const [name, v] of Object.entries(theme.lineHeight ?? {}))
    lines.push(`  --leading-${name}: ${v};`)
  for (const [name, v] of Object.entries(theme.fontFamily ?? {}))
    lines.push(`  --font-${name}: ${v};`)

  lines.push("\n  /* radius / shadow / breakpoints */")
  for (const [name, v] of Object.entries(theme.borderRadius ?? {}))
    lines.push(`  --radius-${name}: ${v};`)
  for (const [name, v] of Object.entries(theme.boxShadow ?? {}))
    lines.push(`  --shadow-${name}: ${v};`)
  for (const [name, v] of Object.entries(theme.screens ?? {}))
    lines.push(`  --breakpoint-${name}: ${v};`)

  lines.push("}")
  return lines.join("\n")
}

const SHADCN_BRIDGE = `
/* --- shadcn/ui semantic token bridge --- */
:root {
  --radius: 0.5rem;

  --background: #ffffff;
  --foreground: var(--color-solid-gray-900);
  --card: #ffffff;
  --card-foreground: var(--color-solid-gray-900);
  --popover: #ffffff;
  --popover-foreground: var(--color-solid-gray-900);
  --primary: var(--color-key-900);
  --primary-foreground: #ffffff;
  --secondary: var(--color-solid-gray-100);
  --secondary-foreground: var(--color-solid-gray-900);
  --muted: var(--color-solid-gray-50);
  --muted-foreground: var(--color-solid-gray-600);
  --accent: var(--color-key-50);
  --accent-foreground: var(--color-key-900);
  --destructive: var(--color-error-1);
  --destructive-foreground: #ffffff;
  --border: var(--color-solid-gray-300);
  --input: var(--color-solid-gray-300);
  --ring: var(--color-focus-yellow);
}

.dark {
  --background: var(--color-solid-gray-900);
  --foreground: #ffffff;
  --border: var(--color-solid-gray-700);
  --input: var(--color-solid-gray-700);
}
`

function build(theme: Theme) {
  const cssOut = `${ATTRIBUTION}\n${css(theme)}\n${SHADCN_BRIDGE}`
  const tokensOut =
    JSON.stringify(
      {
        $comment:
          "Portions derived from digital-go-jp/design-system-example-components-react. MIT License. See THIRD_PARTY_LICENSES.md.",
        ...theme,
      },
      null,
      2
    ) + "\n"
  return { cssOut, tokensOut }
}

function main() {
  const check = process.argv.includes("--check")
  const theme = loadTheme()
  const { cssOut, tokensOut } = build(theme)

  const cssPath = join(STYLES, "digital-agency.css")
  const tokensPath = join(STYLES, "digital-agency.tokens.json")

  if (check) {
    const stale =
      !existsSync(cssPath) ||
      readFileSync(cssPath, "utf8") !== cssOut ||
      !existsSync(tokensPath) ||
      readFileSync(tokensPath, "utf8") !== tokensOut
    if (stale) {
      console.error(
        "Theme files are out of date. Run `pnpm generate:theme` and commit the result."
      )
      process.exit(1)
    }
    console.log("Theme files are up to date.")
    return
  }

  writeFileSync(cssPath, cssOut)
  writeFileSync(tokensPath, tokensOut)
  console.log(
    "Wrote src/styles/digital-agency.css and digital-agency.tokens.json"
  )
}

main()
